services:
  flask:
    env_file:
      - config/.env.prod
    container_name: llm_proxy_flask
    build: .
    ports:
      - "5000:5000"
    networks:
      - backend
    environment:
      - SCRIPT_NAME=/sws-llm-proxy
      - FLASK_APP=wsgi:app
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    env_file:
      - config/.env.prod
    container_name: llm_proxy_postgres
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  backend:
