services:
  flask:
    env_file:
      - config/.env.dev
    container_name: llm_proxy_flask
    build: .
    ports:
      - "127.0.0.1:5123:5000"
    networks:
      - backend
    environment:
      - FLASK_APP=wsgi:app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    entrypoint:
      ["/bin/sh", "-c", "/app/init/init_app_dev.sh"]
  db:
    env_file:
      - config/.env.dev
    container_name: llm_proxy_postgres
    image: postgres
    restart: always
    expose:
      - "5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$PGUSER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  backend:
