"""Initial migration

Revision ID: 5dd5b1f4b994
Revises: 
Create Date: 2025-02-13 10:27:50.950069

"""
import os 
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '5dd5b1f4b994'
down_revision = None
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash

# Generate a hashed password
ADMIN_PW = os.environ.get("ADMIN_PW")
hashed_pw = generate_password_hash(ADMIN_PW)

def upgrade():
    # Create user table
    op.create_table(
        'user',
        sa.Column('id', sa.String(length=200), nullable=False),
        sa.Column('pw_hash', sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Insert admin user into the new table
    conn = op.get_bind()
    conn.execute(text("""   INSERT INTO "user" (id, pw_hash) 
                            SELECT :id, :pw_hash 
                            WHERE NOT EXISTS (SELECT 1 FROM "user" WHERE id = :id)
                        """), {"id": "admin", "pw_hash": hashed_pw})



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
