"""extend data model

Revision ID: 8c28276cb44b
Revises: 5dd5b1f4b994
Create Date: 2025-03-12 12:20:03.468548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c28276cb44b'
down_revision = '5dd5b1f4b994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('encoding_model', sa.String(length=400), nullable=True),
    sa.Column('provider', sa.String(length=400), nullable=True),
    sa.Column('price_input_token', sa.Float(), nullable=True),
    sa.Column('price_output_token', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('used_budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('api_key', sa.String(length=400), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=False)
        batch_op.alter_column('pw_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pw_hash',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('api_key')
        batch_op.drop_column('used_budget')
        batch_op.drop_column('budget')

    op.drop_table('model')
    # ### end Alembic commands ###
